version: '3.8'

services:
  loza-rufeil-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public:/app/public
    ports:
      - "3020:3020"
    env_file:
      - .env