FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./

RUN apk add --no-cache chromium chromium-chromedriver fontconfig

RUN apk update && apk upgrade && \
    apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    npm \
    yarn \
    git

RUN apk update && apk add chromium

# Instala las dependencias necesarias
RUN npm install -g jsreport@3.4.0 jsreport-core@2.10.1 jsreport-chrome-pdf@1.10.0 moment@2.29.1

# Instalar dependencias
RUN npm install
RUN npm install -g ts-node typescript

# Copiar el resto del código fuente
COPY . .

# Comando por defecto para el contenedor
CMD ["npx","nodemon"]
