version: '3.8'

services:
  loza-rufeil-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:/etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:ro
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/privkey.pem:/etc/letsencrypt/live/nekoadmin.com.ar-0002/privkey.pem:ro
      - ./public:/app/public
      - ./views:/app/views
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - '3020:3020'
    env_file:
      - .env
